# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Gustavo',
                'doc_host': 'https://g.diaz14.github.io',
                'git_url': 'https://github.com/g.diaz14/Gustavo',
                'lib_path': 'Gustavo'},
  'syms': {'Gustavo.core': {'Gustavo.core.foo': ('core.html#foo', 'Gustavo/core.py')}}}
