project:
  type: website

lang: es
format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
     

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar: 
    search: true
    background: black
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]